import Link from "next/link";
import logo from "@/assets/logo.png";
/**Every class defined in this module will be available as a property on this imported object */
import classes from "./main-header.module.css";
import Image from "next/image";
import MainHeaderBackground from "./main-header-background";
import NavLink from "./nav-link";

const MainHeader = () => {
  return (
    <>
      <MainHeaderBackground />
      <header className={classes.header}>
        <Link href="/" className={classes.logo}>
          {/**
           * Unlike in React projects, we can't just pass the image like this(src={logo}).
           * Instead we have to access the "src" property. Because this imported logo in NextJS projects
           * will be an object where the path to the image is stored under this "src" property.
           */}
          {/* <img src={logo.src} alt="logo" /> */}
          {/**
           * In NextJS we have a special built-in "Image" component which is recommended to use
           * because it helps us to output images in a more optimized way.For example lazy-loading images
           * under the hood; so they're only displayed if they're visible on the page.
           * It can also simplify the process of setting up resonsive images, etc.
           *
           * By using this, we can now oass overall logo object as the "src".
           * Because this object that's generated by NextJS contains useful information
           * that's used under the hood by this "Image" component to display it in optimize way.
           * For example it automatically detecs the size of this image.
           *
           * If we inspect the image on the console, we'll see that this image element
           * has a couple of extra attributes which we didn't add. For exmaple:
           * loading="lazy" => Makes sure that the image is lazy loaded.
           * width, height  => It automatically inferred width, height but we could overwrite these too.
           * srcset         => Ensures that different sized images are loaded depending on the viewport &
           *                   the device we're using to visit the website.
           * It will also automatically serve the image in the best file format for the browser
           * that's being by the user(ex: WebP). We can check this in the "Networl" tab.
           *
           * priority: When true, the image will be considered high priority & preload.
           *           Lazy loading is automatically disabled for images using priority.
           */}
          <Image src={logo} alt="logo" priority />
          Next-Level Food
        </Link>

        <nav className={classes.nav}>
          <ul>
            <li>
              <NavLink href="/meals">Browse Meals</NavLink>
            </li>
            <li>
              <NavLink href="/community">Foodies Commiunity</NavLink>
            </li>
          </ul>
        </nav>
      </header>
    </>
  );
};

export default MainHeader;
