import type { Metadata } from "next";
import "../globals.css";
import MainHeader from "@/components/main-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="page">
      <MainHeader />
      {children}
    </div>
  );
}
