/**
 * "error" file is reserved file in NextJS which will handle potential errors
 * that might be generated by out pages & components.(Ex: Loading data fails.)
 * This component will be rendered by NextJS whenever an error occurs.
 * It will only handle errors that occurs in the page that sits in the same folder
 * or any nested page or layout.
 * We could also add this on the root folder of our app to catch any error
 * that's cost anywhere in any of our pages.(We can be as granular as needed.)
 * 
 * This "error" file must be a client component, so we could also catch
 * errors on the client side too(After the page was rendered on the server).
 */

"use client";

interface Props {
  // Next js will automatically pass these props to this component.

  /**
   * Accessing the error that was occured.
   * NOTE: The actual error message will be hidden by NextJS,
   * so we don't accidentally expose it to users.
   */
  error: Error;
}
const ErrorPage = ({}: Props) => {
  return (
    <main className="error">
      <h1>An error occurred!</h1>
      <p>Failed to create meal!</p>
    </main>
  );
};

export default ErrorPage;
