/**
 * "layout" is reserved name in the file-base routing which returns a React component.
 * It's a wrapper around the page content(It defines the shell around one or more pages).
 * Every NextJS project needs at least one root layout file(One layout file at the top of the "app" folder.).
 *
 * If we had a nested layout, then that layout would become active
 * for the related pages inside that folder,
 * but it would itself be nested into the root layout.
 * So the root layout will always be active.
 */

/**
 * "icon" another special file name.
 * If we add an image called "icon" in the "app folder" it'll be used as a favicon by NextJS.
 */

import type { Metadata } from "next";
import "./globals.css";

/**
 * Head element(Meta data)
 * "metadata" also a reserved name.
 * If we export a variable with this name the meta data will be applied
 * to all the pages that are covered by this layout.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  /**The content of the page that's currently active. */
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /**
   * This is neccessary in a NextJS project in the root layout
   * to set up the general HTML skeleton of the website.
   */
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
